plugin:
    name: 'eugene3993.seo::lang.plugin.name'
    description: 'eugene3993.seo::lang.plugin.description'
    author: Eugene3993
    icon: icon-sitemap
    homepage: ''
permissions:
    eugene3993.seo.sitemap:
        tab: 'SEO Pro'
        label: 'eugene3993.seo::lang.permissions.labels.sitemap'
    eugene3993.seo.meta:
        tab: 'SEO Pro'
        label: 'eugene3993.seo::lang.permissions.labels.meta'
    eugene3993.seo.settings:
        tab: 'SEO Pro'
        label: 'eugene3993.seo::lang.permissions.labels.settings'
